### ISSUE TITLE
Improved handling of preemption  on GCE

### ISSUE THREAD

**Issue by a-palchikov** [gravitational/robotest#149]
The whole point of using preemptible instances is being able to save money on throw-away test runs. Using preemptible instances is ~3rd the price of a regular instance - with that in mind, if the instance is preempted more than 3 times, the pricing advantage disappears.
An optimization idea is turning off preemption after the first failure.
Another simpler idea is turning preemption off entirely and bringing the number of retries back to `3` as it's been [bumped](https://github.com/gravitational/robotest/pull/138/files#diff-f9e91517c31865c93494fba9442eeff9R58) to `10` with preemption support.

**Comment by wadells** [comment]
We're unlikely to invest in this.  Preemption has been turned off in almost all uses of robotest as it wasn't found worthwhile.  I suspect efforts would be better invested in migrating workloads to our colocated rack if we want to optimize for cost savings.
