### ISSUE TITLE
Add more upgrade scenarios from released buids to development builds

### ISSUE THREAD

**Issue by r0mant** [gravitational/robotest#155]
More upgrade tests are needed because patch versions can introduce regressions which are not caught if the “base” upgrade version remains unchanged.

Let’s assume that:

* The current release branch is 6.1 and the next release is 6.1.7.
* The first version of the previous LTS release is 5.5.0
* The latest patch version of the previous LTS release is 5.5.24

Given that, the following upgrade scenarios should be additionally tested on each PR:

- [ ] From 5.5.0 (first release of previous LTS).
- [ ] From 5.5.24 (latest patch release of previous LTS).
- [ ] From 6.1.0 (first release of current branch).
- [ ] From 6.1.6 (from previous release of current branch).

**Comment by r0mant** [comment]
@wadells Here's what the customer said about their releases in the field:

> We have released 5.2.12, 5.5.18, 5.5.19, 5.5.20, 5.5.28 and 5.5.36
> The only 5.0.x is 5.0.28

So let's make sure we test upgrades from each of these in 5.5 branch.

For 5.0.28, I would look into adding a two-step upgrade, 5.0.28->5.2.12->5.5.latest.

**Comment by wadells** [comment]
> For 5.0.28, I would look into adding a two-step upgrade, 5.0.28->5.2.12->5.5.latest.

I'd like to leave 2 step upgrades out of scope for the initial work.  I've filed #180 to track that work.

**Comment by wadells** [comment]
These scenarios are done in all active branches (save 6.3, which won't be active once 7.0 is cut in a week or so).  I've filed https://github.com/gravitational/robotest/issues/186 as a followup to test upgrading from dev builds on older releases to stable newer releases.
