### ISSUE TITLE
Add support for "intermediate" upgrades

### ISSUE THREAD

**Issue by r0mant** [gravitational/robotest#156]
An "intermediate" upgrade is the upgrade b/w non-adjacent LTS versions, for example, 5.0 -> 5.5 (through "intermediate" hop of 5.2 that's done automatically).

This is currently only supported in 5.5 branch but once this is forward-ported to later versions, we should be testing these scenarios as well.

**Comment by wadells** [comment]
This is already in place for 5.5.x as seen at:

https://github.com/gravitational/gravity/blob/404365d3425d8a8fe5ce7d2c8d3a8f1dfb7d4e60/Jenkinsfile#L77
https://github.com/gravitational/gravity/blob/404365d3425d8a8fe5ce7d2c8d3a8f1dfb7d4e60/Makefile#L464-L466

There is no further work to be done here until  https://github.com/gravitational/gravity/issues/1115 lands.

Please reopen when https://github.com/gravitational/gravity/issues/1115  is complete or with more information if I'm misunderstanding
