### ISSUE TITLE
Add scenario where join does not wait for install to finish

### ISSUE THREAD

**Issue by r0mant** [gravitational/robotest#157]
Join scenario where gravity join command is waiting for the ongoing install operation to complete. This has regressed in the past. Could probably just modify the existing “resize” test case so it does not wait for install to complete before launching join.

**Comment by wadells** [comment]
>  This has regressed in the past.

@r0mant Can you please link to a customer bug or provide any additional detail about where/how this has failed in the past?  Any additional info here will help me prioritize and implement a useful test case.

**Comment by wadells** [comment]
This is how robotest already functions, as of v2.1.0:

https://github.com/gravitational/robotest/blob/v2.1.0/infra/gravity/cluster_install.go#L102-L121
