### ISSUE TITLE
Add scenario with joining a non-master node

### ISSUE THREAD

**Issue by r0mant** [gravitational/robotest#159]
Explicitly joining non-master nodes via manifest role labels. Right now all our test clusters consist of masters which has bitten us in the past. Example scenario:

- [ ] Install 1-node cluster.
- [ ] Add a regular worker using appropriate manifest profile.

**Comment by wadells** [comment]
> Right now all our test clusters consist of masters which has bitten us in the past.

@r0mant can you please link to an issue or any give any details about when/how this has bitten us in the past?  This will help me prioritize this task and make sure the impact in the wild is adequately exercised.
