### ISSUE TITLE
Allow robotest to configure kubernetes applications running inside Gravity

### ISSUE THREAD

**Issue by r0mant** [gravitational/robotest#160]
Use a more complicated cluster image for the tests that has some application resources and things like install/upgrade/join/remove hooks so these paths are covered.

Currently we’re using base gravity image which has neither any of the hooks nor the actual application resources.

**Comment by wadells** [comment]
It looks like the unfinished kubernetes config parameter removed here may have been intended to support this use case: https://github.com/gravitational/robotest/pull/192/files#diff-57596aab97dd40eec3b9f33a35d50e89L91-L92

**Comment by wadells** [comment]
Addressed by gravitational/gravity#1967 and https://github.com/gravitational/gravity/pull/2133.
