### ISSUE TITLE
Reanimate wizard-based UI installer testing

### ISSUE THREAD

**Issue by r0mant** [gravitational/robotest#162]
We used to have a Selenium-based test that would test browser-based install flow which would click the buttons, fill out the forms, initiate installation, wait for it to complete and so on.

With Gravity 6.0 release the whole UI has been reworked so all those tests are not working now. Ideally we would bring them back as UI-based install also regresses sometimes.

**Comment by alex-kovoy** [comment]
Small correction, we used a chrome-web driver instead of Selenium.
