### ISSUE TITLE
Measure Robotest PR dollar costs

### ISSUE THREAD

**Issue by wadells** [gravitational/robotest#164]
Develop a methodology to measure the cost of each Robotest PR run, as well as monthly cost growth forecast (including PR velocity and change over time, as well as any change in a single Robotest run cost)

Context:

Robotest is run against every Gravity PR: https://github.com/gravitational/gravity/pulls
These runs provision and tear down resources from a cloud provider (GCP as of 2019-12, previously AWS).  Although Gravitational has some trial cloud credit for free, we need to understand the current cost of testing and how it may grow as we invest in a larger matrix of test.

**Comment by r0mant** [comment]
I think this is an interesting metric for sure. I wonder if that becomes less relevant if our end game is to run robotest on our own servers Sasha is building (and maybe that should be the focus). Not sure how soon it will come though so... just saying... cc @klizhentas
