### ISSUE TITLE
Define & Baseline Robotest KPIs

### ISSUE THREAD

**Issue by wadells** [gravitational/robotest#166]
Define crisp and calculable key performance indicators for robotest.

Consider:
 - developer time costs (clock time for runs)
 - cloud hardware costs
 - local datacenter/metal costs (& administration costs)
 - bugs caught by robotest
 - spurious failures (e.g. infra related, no product bug caught)
 - product commit/feature velocity (how much changes per time unit)
 - what can be/is cost effective to measure

Come up with either pure or aggregate metrics from these and a process (hopefully automated) to calculate the KPIs on reoccurring basis.  Baseline where Robotest is at today for all KPIs before starting on any substantive changes.

**Comment by r0mant** [comment]
@wadells Honestly, I think that the most important metric which we should aim to drive to 0 is (as we discussed on our 1x1's) "escapes", i.e. regressions that made it to releases. Just mentioning here cause I don't see it mentioned above.
