### ISSUE TITLE
Allow licence specific testing

### ISSUE THREAD

**Issue by r0mant** [gravitational/robotest#168]
Robotest should also test some scenarios specific to the enterprise edition to prevent regressions in the enterprise-specific paths (see https://github.com/gravitational/gravity/issues/989 for example).

A good candidate is installing a cluster image that requires a license. For reference, there's an example on how to do that in our test plan: [Licensing & Encryption](https://github.com/gravitational/gravity/blob/master/docs/6.x/testplan.md#licensing--encryption-enterprise-edition).

**Comment by wadells** [comment]
I'm narrowing the scope of this issue from "Robotest should also test some scenarios specific to the enterprise edition" to only "Robotest should test installing a cluster image that requires a license".  Other enterprise specific scenarios should be called out in separate issues.

In #192 (review) @r0mant suggested that we exercise the --license flag in Robotest.

**Comment by wadells** [comment]
Generate the license, pass the license flag, update the license (application manifest will need the license). Validate something fails when we don't have the license.
