### ISSUE TITLE
Investigate depending on terraform via go modules

### ISSUE THREAD

**Issue by wadells** [gravitational/robotest#172]
If robotest continues to be committed to terraform, I want to look into depending on terraform via the go tool chain instead of out-of-band installation.

## Context

As of 06d38de, Robotest expects the terraform binary to be present on the system, the path to it passed via the cryptically named `script_path:` key in the -provision flag yaml.

https://github.com/gravitational/robotest/blob/06d38de451f38514c9fe4899fe7b2a98f2b7d319/docker/suite/run_suite.sh#L126

In addition to the terraform binary itself, a handful of provider plugins dependencies are dealt with out of band:

https://github.com/gravitational/robotest/blob/06d38de451f38514c9fe4899fe7b2a98f2b7d319/docker/Makefile#L10-L14

These are curled and installed in the container:

https://github.com/gravitational/robotest/blob/06d38de451f38514c9fe4899fe7b2a98f2b7d319/docker/suite/Dockerfile#L25-L34

However, terraform is written in go: https://github.com/hashicorp/terraform so we should be able to use the native go toolchain to depend on it.  This will require understanding why we deal with these dependencies the way we do currently.

I believe depending on terraform via the native would provide the following advantages:

* Easier setup of non-dockerized run environments.
* The above will assist with new contributor onboarding.
* Simplified build process.
* Simplified run process (docker || undocumented setup not required)

**Comment by wadells** [comment]
An example of the type of failure that occurs when plugins are not set up properly:

```
INFO[0000] Command started.                              cluster= cmd=/home/walt/.dotfiles/bin/terraform init -input=false -get-plugins=false -plugin-dir=/etc/terraform/plugins /home/walt/git/robotest/wd_suite/state/walt/install-1/ubuntu18/overlay2/3n/tf pid=31303 provisioner=terraform state-dir="/home/walt/git/robotest/wd_suite/state/walt/install-1/ubuntu18/overlay2/3n/tf"
INFO[0000] Command finished.                             cluster= cmd=/home/walt/.dotfiles/bin/terraform init -input=false -get-plugins=false -plugin-dir=/etc/terraform/plugins /home/walt/git/robotest/wd_suite/state/walt/install-1/ubuntu18/overlay2/3n/tf error="exit status 1" output="2020/01/24 16:01:51 [WARN] Log levels other than TRACE are currently unreliable, and are supported only for backward compatibility.
  Use TF_LOG=TRACE to see Terraform's internal logs.
  ----

Initializing the backend...

Initializing provider plugins...

Missing required providers.

The following provider constraints are not met by the currently-installed
provider plugins:

* google (>= 1.19)
* random (>= 2.0)
* template (>= 1.0)

Terraform can automatically download and install plugins to meet the given
constraints, but this step was skipped due to the use of -get-plugins=false
and/or -plugin-dir on the command line.

If automatic installation is not possible or desirable in your environment,
you may manually install plugins by downloading a suitable distribution package
and placing the plugin's executable file in one of the directories given in
by -plugin-dir on the command line, or in the following directory if custom
plugin directories are not set:
    terraform.d/plugins/linux_amd64


Error: missing provider "template"



Error: missing provider "google"



Error: missing provider "random"


" pid=31303 provisioner=terraform state-dir="/home/walt/git/robotest/wd_suite/state/walt/install-1/ubuntu18/overlay2/3n/tf"
```

**Comment by wadells** [comment]
@a-palchikov @alex-kovoy @r0mant Do any of you have historical context or know why Robotest depends on terraform & provisioners via out-of-band binary install?  See https://github.com/gravitational/robotest/issues/172#issue-555008615 for what I mean by out-of-band binary install.

I've filed this issue as something I'd like to get to, but not an immediate priority.  But perhaps one of you knows why Robotest is set up this way, and can save me an investigation down the road.

**Comment by a-palchikov** [comment]
@wadells I'm not quite following what you're getting at?
Yes, the terraform binary is expected to be part of the robotest environment but it is not specified with the `script_path` attribute - the attribute specifies the location of the terraform scripts.
The reason why terraform is used "out-of-band" is simple - it was easier to hook up and frankly using it as a library has never been seriously discussed iirc. It does not mean it is not a viable solution though as I'd guess it would probably solve quite a few issues but I cannot really tell without taking a good look at it.

One thing that had always bothered me is error handling - it is impossible to determine the reason why terraform (as a binary) is failing and make educated failure handling decisions - I'm not sure how much going with tighter integration will help here.

Also I'm not sure if you're hinting at the fact that we use terraform scripts instead of infrastructure as code (for example [pulumi](https://github.com/pulumi/pulumi)) - no idea how beneficial this will be yet.

**Comment by wadells** [comment]
> @wadells I'm not quite following what you're getting at?
> Yes, the terraform binary is expected to be part of the robotest environment but it is not specified with the `script_path` attribute - the attribute specifies the location of the terraform scripts.

Whoops!  My mistake.

> The reason why terraform is used "out-of-band" is simple - it was easier to hook up and frankly using it as a library has never been seriously discussed iirc. It does not mean it is not a viable solution though as I'd guess it would probably solve quite a few issues but I cannot really tell without taking a good look at it.

Thanks.  This is the information I was looking for, and what I suspected. I wanted to double check that there weren't technical or business reasons for using the binary (e.g. We tried native dependencies, but it failed) before I sink time into investigating native dependencies.  Not that this is on the roadmap in the next month or two anyhow.

> One thing that had always bothered me is error handling - it is impossible to determine the reason why terraform (as a binary) is failing and make educated failure handling decisions - I'm not sure how much going with tighter integration will help here.

I'll keep error exposure in mind when I get to this.

> Also I'm not sure if you're hinting at the fact that we use terraform scripts instead of infrastructure as code (for example [pulumi](https://github.com/pulumi/pulumi)) - no idea how beneficial this will be yet.

I haven't looked at pulumi or other terraform alternatives all yet -- thanks for mentioning it.  IMO, terraform is infrastructure as code, and is relatively state of the art too.  Admittedly, the state of the art leaves lots to be desired, but I'm not presently convinced that there are better alternatives.

@klizhentas mentioned wanting to move towards more native kubernetes for robotest in a meeting, but I don't yet grok his vision.
