### ISSUE TITLE
Use custom service user/group ID for installation

### ISSUE THREAD

**Issue by r0mant** [gravitational/robotest#189]
Gravity provides a way to override default service user ID (1000 in older versions, 980665 in newer ones) by providing a flag at install time:

```
gravity install --service-uid=666 --service-gid=777
```

As it is this scenario is not tested by robotest at the moment. We should modify one of our install/upgrade scenarios to use custom UIDs.

This should be configurable in the robotest script (https://github.com/gravitational/gravity/blob/master/build.assets/robotest_run_suite.sh) with ability to provide them as test parameters e.g.

```
upgrade3lts={${cluster_size},"os":"${os}","storage_driver":"${storage_driver}","from":"/telekube_${release}.tar","service_uid":"666","service_gid":"777"}
```

**Comment by wadells** [comment]
This exercises the customer bug https://github.com/gravitational/gravity/issues/1279

**Comment by wadells** [comment]
WIP here: https://github.com/wadells/robotest/tree/uid-gid

A first run (install only) that uses these flags: [logs](https://console.cloud.google.com/logs/viewer?authuser=0&expandAll=false&project=kubeadm-167321&minLogLevel=0&timestamp=2020-03-25T21:11:57.234000000Z&customFacets=&limitCustomFacetWidth=true&advancedFilter=resource.type%3D%22project%22%0Alabels.__uuid__%3D%22ed3623f1-89c4-47d5-819c-a30e003afadf%22%0Alabels.__suite__%3D%229c9da97a-eef8-4c38-9c94-215b667ff1bb%22%0AjsonPayload.param:%22service_uid%22%0AOR%20jsonPayload.cmd:%22--service-uid%22&dateRangeStart=2020-03-25T20:15:34.543Z&interval=PT1H&scrollTimestamp=2020-03-25T21:08:27.258217922Z&dateRangeEnd=2020-03-25T21:15:34.543Z)

Futher testing needed, particularly trying to repro gravitational/gravity#1279 via the scenario that @a-palchikov described:

5.5.28 -> 5.5.38

I'm not sure if I'll need to put in some extra checks  post upgrade to make sure this setting doesn't regress.  Waiting on a response to this question: https://github.com/gravitational/gravity/issues/1279#issuecomment-604055809
