### ISSUE TITLE
Add the ability to test SELinux

### ISSUE THREAD

**Issue by wadells** [gravitational/robotest#201]
With @a-palchikov's recent work in https://github.com/gravitational/gravity/pull/1108 https://github.com/gravitational/gravity/pull/1172, Gravity now has the ability to run on distros hardened by SELinux.

Robotest should offer consumers (gravity CI mostly) a way to exercise gravity on a SELinux hardened distro.

**Comment by a-palchikov** [comment]
This can be configured in a noninvasive way by setting the [environment variable](https://github.com/gravitational/gravity/blob/7.0.0-rc.5/lib/defaults/defaults.go#L868) `GRAVITY_SELINUX=true` for the gravity install process.

**Comment by wadells** [comment]
> This can be configured in a noninvasive way by setting the [environment variable](https://github.com/gravitational/gravity/blob/7.0.0-rc.5/lib/defaults/defaults.go#L868) `GRAVITY_SELINUX=true` for the gravity install process.

@a-palchikov Can you elaborate a bit more?

Upon preliminary investigation, neither install nor join has environment variables plumbed through:

https://github.com/gravitational/robotest/blob/95865405776d1185dcb94038ceb7ae65ec0aaed9/infra/gravity/node_commands.go#L263
https://github.com/gravitational/robotest/blob/95865405776d1185dcb94038ceb7ae65ec0aaed9/infra/gravity/node_commands.go#L354
https://github.com/gravitational/robotest/blob/95865405776d1185dcb94038ceb7ae65ec0aaed9/lib/ssh/run_parse.go#L21

So I don't think this will be particularly non-invasive.  Unless you're suggesting we set this environment variable elsewhere (e.g. the node's shell profile).

For consistency's sake, I'd suggest we go with gravity CLI flags and the `InstallParam` struct, as this is how most (all?) install configuration is handled

https://github.com/gravitational/robotest/blob/95865405776d1185dcb94038ceb7ae65ec0aaed9/infra/gravity/node_commands.go#L267-L280

**Comment by a-palchikov** [comment]
By non-invasive I meant for a particular installer - not the robotest binary which will need to set corresponding environment variables (perhaps only for relevant distributions).

**Comment by wadells** [comment]
It appears that the current robtest selinux triggerst don't actually enable gravity's SELinux support.  Reopening.
