### ISSUE TITLE
Allow centos:8 testing

### ISSUE THREAD

**Issue by wadells** [gravitational/robotest#258]
As seen in [these logs](https://console.cloud.google.com/logs/viewer?authuser=0&expandAll=false&project=kubeadm-167321&minLogLevel=0&timestamp=2020-07-15T18:40:01.804000000Z&customFacets=&limitCustomFacetWidth=true&advancedFilter=resource.type%3D%22project%22%0Alabels.__uuid__%3D%2293cc3521-5cce-4be7-bcb8-caa1b51b2f19%22%0Alabels.__suite__%3D%221b8adc0b-3529-440a-8750-b573bd9a42e3%22&dateRangeStart=2020-07-15T17:40:17.904Z&dateRangeEnd=2020-07-15T18:40:17.904Z&interval=PT1H&scrollTimestamp=2020-07-15T17:49:02.411426819Z), centos:8 robotest runs fail bootstrap. A promising lead is:

```
 [0;1;31m[0m2020/07/15 17:48:46 GCEMetadataScripts: startup-script: + semanage fcontext -a -t user_home_t /home/centos [0;1;31m[0m2020/07/15 17:48:46 GCEMetadataScripts: startup-script: /tmp/metadata-scripts563044633/startup-script: line 13: semanage: command not found [0;1;31m[0m2020/07/15 17:48:46 GCEMetadataScripts: startup-script: + (( count++ )) [0;1;31m[0m2020/07/15 17:48:46 GCEMetadataScripts: startup-script: + (( count==20 )) [0;1;31m[0m2020/07/15 17:48:46 GCEMetadataScripts: startup-script: + sleep 5
```

**Comment by a-palchikov** [comment]
Looks like it needs to be installed with `yum install -y policycoreutils-python`
